zn.define([
    './ZNPluginSurveyEvent',
    './ZNPluginSurveyEventField',
    './ZNPluginSurveyEventType',
    './ZNPluginSurveyPaper',
    './ZNPluginSurveyPaperType',
    './ZNPluginSurveyPaperAnswer',
    './ZNPluginSurveyPaperTopic',
    './ZNPluginSurveyPaperTopicItem',
    './ZNPluginSurveyUser'
]);
